networks:
  fund-pipeline:
    name: fund-pipeline

services:
  zookeeper:
    networks:
      - fund-pipeline
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    networks:
      - fund-pipeline
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    image: postgres:16-alpine
    container_name: postgres-fund-balance
    networks:
      - fund-pipeline
    environment:
      POSTGRES_USER: funduser
      POSTGRES_PASSWORD: fundpass
      POSTGRES_DB: fund_balance
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../db/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U funduser -d fund_balance"]
      interval: 5s
      timeout: 5s
      retries: 5

  spark-master-fund-balance:
    image: apache/spark:3.5.1
    container_name: spark-master-fund-balance
    networks:
      - fund-pipeline
    environment:
      - SPARK_MODE=master
      - SPARK_DRIVER_EXTRA_CLASSPATH=/opt/spark/jars-extra/*
      - SPARK_EXECUTOR_EXTRA_CLASSPATH=/opt/spark/jars-extra/*
    ports:
      - "7077:7077"
      - "8081:8080"
    volumes:
      - ../spark:/opt/spark-apps
      - ../jars:/opt/spark/jars-extra
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master --host spark-master-fund-balance --port 7077 --webui-port 8080

  spark-worker-fund-balance:
    image: apache/spark:3.5.1
    container_name: spark-worker-fund-balance
    networks:
      - fund-pipeline
    depends_on:
      - spark-master-fund-balance
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master-fund-balance:7077
      - SPARK_DRIVER_EXTRA_CLASSPATH=/opt/spark/jars-extra/*
      - SPARK_EXECUTOR_EXTRA_CLASSPATH=/opt/spark/jars-extra/*
    volumes:
      - ../spark:/opt/spark-apps
      - ../jars:/opt/spark/jars-extra
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master-fund-balance:7077

volumes:
  postgres_data:
